# Introduction to NumPy - Part 01

This notebook provides an introduction to NumPy. This is part 1 of the series.

### Import 

Before we explore more on NumPy, let's import NumPy and print the version being used.

In [1]:
import numpy as np
print('numpy version: {}'.format(np.__version__))

numpy version: 1.16.2


### Array Initialization  

There are multiple ways arrays can be initialized in NumPy. Those options include:  

- From existing data: Creates a new array using existing data  
- Ones:  Creates a new array of given shape and type, filled with ones  
- Ones-Like: Creates an array of ones with the same shape and type as a given array   
- Zeros: Creates a new array of given shape and type, filled with zeros  
- Zeros-Like: Creates an array of zeros with the same shape and type as a given array    
- Full: Creates a new array of given shape and type, filled with fill_value  
- Full-Like: Creates a full array with the same shape and type as a given array  
- Eye: Creates a 2-D array with ones on the diagonal and zeros elsewhere  
- Identity: Creates the identity array  
- Random: Creates a random array of given size  

In [2]:
# initialize a numpy array using custom data
data_1d = np.array([1, 2, 3, 4, 5])
data_2d = np.array([[1, 2, 3, 4, 5],[6,7,8,9,10]], dtype='complex') # specify the data type

# initialize an array with 5 ones
ones = np.ones(5)
ones_like = np.ones_like(data_2d)

# initialize an array with 5 zeros
zeros = np.zeros(5)
zeros_like = np.zeros_like(data_2d)

full = np.full((5,5),3)
full_like = np.full_like(data_2d,3)

# initialize an array with 5 random numbers
random = np.random.random(5)

eye_a = np.eye(2, dtype=int)
eye_b = np.eye(2,3, dtype=int)
eye_c = np.eye(3, k=1) # k: index of the diagonal


identity = np.identity(4)

# print the arrays
print('data_1d: {}'.format(data_1d))
print('data_2d: {}'.format(data_2d))
print('ones: {}'.format(ones))
print('ones_like: {}'.format(ones_like))
print('zeros: {}'.format(zeros))
print('zeros_like: {}'.format(zeros_like))
print('full: {}'.format(full))
print('full_like: {}'.format(full_like))
print('random: {}'.format(random))
print('eye_a: {}'.format(eye_a))
print('eye_b: {}'.format(eye_b))
print('eye_c: {}'.format(eye_c))
print('identity: {}'.format(identity))

# more dimensions
ones = np.ones((4,3,2))
zeros = np.zeros((4,3,2))
random = np.random.random((4,3,2))

print('ones: {}'.format(ones))
print('zeros: {}'.format(zeros))
print('random: {}'.format(random))

data_1d: [1 2 3 4 5]
data_2d: [[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j]
 [ 6.+0.j  7.+0.j  8.+0.j  9.+0.j 10.+0.j]]
ones: [1. 1. 1. 1. 1.]
ones_like: [[1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]]
zeros: [0. 0. 0. 0. 0.]
zeros_like: [[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]]
full: [[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]
full_like: [[3.+0.j 3.+0.j 3.+0.j 3.+0.j 3.+0.j]
 [3.+0.j 3.+0.j 3.+0.j 3.+0.j 3.+0.j]]
random: [0.40502411 0.18812153 0.99176248 0.57391474 0.77799173]
eye_a: [[1 0]
 [0 1]]
eye_b: [[1 0 0]
 [0 1 0]]
eye_c: [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
identity: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
ones: [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
zeros: [[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
ra

### Array Properties

A ndarray has multiple properties. Among them, following are a few useful ones:  
- shape: Nuple of array dimensions    
- ndim: Number of array dimensions   
- size: Number of elements in the array   
- dtype: Data-type of the array’s elements   
- itemsize: Length of one array element in bytes   
- data: Python buffer object pointing to the start of the array’s data.   

In [3]:
# initialize an array with 10 ones
ones = np.ones(10)

print('ones.shape: {}'.format(ones.shape))
print('ones.ndim: {}'.format(ones.ndim))
print('ones.size: {}'.format(ones.size))
print('ones.dtype: {}'.format(ones.dtype))
print('ones.itemsize: {}'.format(ones.itemsize))
print('ones.data: {}'.format(ones.data))


ones.shape: (10,)
ones.ndim: 1
ones.size: 10
ones.dtype: float64
ones.itemsize: 8
ones.data: <memory at 0x7f00a400f588>


### Array Ranges

Following are a few options to create arrays from using ranges:

- arange: evenly spaced values within a given interval (excluding stop)  
- linspace: evenly spaced numbers over a specified interval  


In [4]:
a = np.arange(15)
b = np.arange(10,50,5)
c = np.arange(0,5,.2)

f = np.linspace(2.0, 3.0, num=5)
g = np.linspace(2.0, 3.0, num=5, endpoint=False)
h = np.linspace(2.0, 3.0, num=5, retstep=True)

print('a: {}'.format(a))
print('b: {}'.format(b))
print('c: {}'.format(c))

print('f: {}'.format(f))
print('g: {}'.format(g))
print('h: {}'.format(h))


print('a.shape: {}'.format(a.shape))
print('a.ndim: {}'.format(a.ndim))
print('a.size: {}'.format(a.size))
print('a.dtype: {}'.format(a.dtype))
print('a.itemsize: {}'.format(a.itemsize))
print('a.data: {}'.format(a.data))
print('type(a): {}'.format(type(a)))

print('b.shape: {}'.format(b.shape))
print('b.ndim: {}'.format(b.ndim))
print('b.size: {}'.format(b.size))
print('b.dtype: {}'.format(b.dtype))
print('b.itemsize: {}'.format(b.itemsize))
print('b.data: {}'.format(b.data))
print('type(b): {}'.format(type(b)))

a: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
b: [10 15 20 25 30 35 40 45]
c: [0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8]
f: [2.   2.25 2.5  2.75 3.  ]
g: [2.  2.2 2.4 2.6 2.8]
h: (array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)
a.shape: (15,)
a.ndim: 1
a.size: 15
a.dtype: int64
a.itemsize: 8
a.data: <memory at 0x7f00a400f588>
type(a): <class 'numpy.ndarray'>
b.shape: (8,)
b.ndim: 1
b.size: 8
b.dtype: int64
b.itemsize: 8
b.data: <memory at 0x7f00a400f588>
type(b): <class 'numpy.ndarray'>


### Shape Manipulations
NumPy provides many options to do shape manipulations such as:

- reshape: Returns an array containing the same data with a new shape   
- ravel: Return a flattened array  
- flatten: Return a copy of the array collapsed into one dimension
- repeat: Repeat elements of an array  
- sort: Sort an array in-place  
- take: Return an array formed from the elements of a at the given indices  
- transpose :  matrix transpose  
- inverse : matrix inverse  

In [5]:
a = np.arange(15).reshape(3, 5)
b = np.arange(24).reshape(2,3,4)

print('a: {}'.format(a))
print('b: {}'.format(b))

print('b.flatten(): {}'.format(b.flatten()))
print('b.ravel(): {}'.format(b.ravel()))

print('np.repeat(3, 4): {}'.format(np.repeat(3, 4)))

x = np.array([[1,2],[3,4]])
print('x: {}'.format(x))
print('np.repeat(x, 2): {}'.format(np.repeat(x, 2))) # 2 is the number of repetitions for each element. repeats is broadcasted to fit the shape of the given axis.
print('np.repeat(x, 3, axis=1): {}'.format(np.repeat(x, 3, axis=1)))
print('np.repeat(x, [1, 2], axis=0): {}'.format(np.repeat(x, [1, 2], axis=0)))

c = np.array([[4,3], [2,1]])
print('c: {}'.format(c))
c.sort(axis=1)
print('c (after sort over axis=1): {}'.format(c))
c.sort(axis=0)
print('c (after sort over axis=0): {}'.format(c))

d = np.array([4, 3, 5, 7, 6, 8])
indices = [0, 1, 4]

print('np.take(d, indices): {}'.format(np.take(d, indices)))
print('np.take(d, [[0, 1], [2, 3]]): {}'.format(np.take(d, [[0, 1], [2, 3]])))

data = np.array([1,2,3,4,5,6])

print('data.reshape(2,3): {}'.format(data.reshape(2,3)))
print('data.reshape(3,2): {}'.format(data.reshape(3,2)))

data = np.arange(1,11,1).reshape(2,5) # array([[1, 2, 3, 4, 5],[6,7,8,9,10]])
ones = np.ones((2,5))
data_2d = np.array([[1,2],[3,4]])
twos = np.full((2,5),2)

print('data.transpose(): {}'.format(data.transpose())) # or data.T
print('np.linalg.inv(data_2d): {}'.format(np.linalg.inv(data_2d)))


a: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
b: [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
b.flatten(): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
b.ravel(): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
np.repeat(3, 4): [3 3 3 3]
x: [[1 2]
 [3 4]]
np.repeat(x, 2): [1 1 2 2 3 3 4 4]
np.repeat(x, 3, axis=1): [[1 1 1 2 2 2]
 [3 3 3 4 4 4]]
np.repeat(x, [1, 2], axis=0): [[1 2]
 [3 4]
 [3 4]]
c: [[4 3]
 [2 1]]
c (after sort over axis=1): [[3 4]
 [1 2]]
c (after sort over axis=0): [[1 2]
 [3 4]]
np.take(d, indices): [4 3 6]
np.take(d, [[0, 1], [2, 3]]): [[4 3]
 [5 7]]
data.reshape(2,3): [[1 2 3]
 [4 5 6]]
data.reshape(3,2): [[1 2]
 [3 4]
 [5 6]]
data.transpose(): [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
np.linalg.inv(data_2d): [[-2.   1. ]
 [ 1.5 -0.5]]


### Joining Arrays   

Following are some routines that can be used to join arrays:  

- concatenate: Join a sequence of arrays along an existing axis  
- stack: Join a sequence of arrays along a new axis  
- column_stack: Stack 1-D arrays as columns into a 2-D array  
- dstack: Stack arrays in sequence depth wise (along third axis)  
- hstack: Stack arrays in sequence horizontally (column wise)  
- vstack: Stack arrays in sequence vertically (row wise)  

In [6]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

print('a: {}'.format(a))
print('b: {}'.format(b))

print('np.concatenate((a, b), axis=0): {}'.format(np.concatenate((a, b), axis=0)))
print('np.concatenate((a, b.T), axis=1): {}'.format(np.concatenate((a, b.T), axis=1)))
print('np.concatenate((a, b), axis=None): {}'.format(np.concatenate((a, b), axis=None)))

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.array([[1],[2],[3]])
d = np.array([[4],[5],[6]])


print('a: {}'.format(a))
print('b: {}'.format(b))
print('c: {}'.format(c))
print('d: {}'.format(d))

print('np.stack((a, b)): {}'.format(np.stack((a, b))))
print('np.stack((a, b), axis=-1): {}'.format(np.stack((a, b), axis=-1)))

print('np.column_stack((a,b)): {}'.format(np.column_stack((a,b))))

print('np.dstack((a,b)): {}'.format(np.dstack((a,b))))
print('np.dstack((c,d)): {}'.format(np.dstack((c,d))))

print('np.hstack((a,b)): {}'.format(np.hstack((a,b))))
print('np.hstack((c,d)): {}'.format(np.hstack((c,d))))

print('np.vstack((a,b)): {}'.format(np.vstack((a,b))))
print('np.vstack((c,d)): {}'.format(np.vstack((c,d))))


a: [[1 2]
 [3 4]]
b: [[5 6]]
np.concatenate((a, b), axis=0): [[1 2]
 [3 4]
 [5 6]]
np.concatenate((a, b.T), axis=1): [[1 2 5]
 [3 4 6]]
np.concatenate((a, b), axis=None): [1 2 3 4 5 6]
a: [1 2 3]
b: [4 5 6]
c: [[1]
 [2]
 [3]]
d: [[4]
 [5]
 [6]]
np.stack((a, b)): [[1 2 3]
 [4 5 6]]
np.stack((a, b), axis=-1): [[1 4]
 [2 5]
 [3 6]]
np.column_stack((a,b)): [[1 4]
 [2 5]
 [3 6]]
np.dstack((a,b)): [[[1 4]
  [2 5]
  [3 6]]]
np.dstack((c,d)): [[[1 4]]

 [[2 5]]

 [[3 6]]]
np.hstack((a,b)): [1 2 3 4 5 6]
np.hstack((c,d)): [[1 4]
 [2 5]
 [3 6]]
np.vstack((a,b)): [[1 2 3]
 [4 5 6]]
np.vstack((c,d)): [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


 ### Array/Matrix Basic Operations  
 
 Following are some of the NumPy operations for Arrays/Matrices:  
 
 - Array/Matrix Operations:
   - \+  : element-wise addition  
   - \-  : element-wise subtraction  
   - \/  : element-wise division   
   - \*  : element-wise multiplication  
   - \** : element-wise square  
   - \<  : element-wise condition  
   - +=  : addition (does not create a new array)  
   - *=  : multiplication (does not create a new array)  
 
- Matrix Operations:  
  - \@  : matrix multiplication  
  - dot : matrix multiplication  
 

In [7]:
# Array Operations

data = np.array([1, 2, 3, 4, 5])
ones = np.ones(5)
zeros = np.zeros(5)
random = np.random.random(5)

print('data: {}'.format(data))
print('ones: {}'.format(ones))
print('zeros: {}'.format(zeros))
print('random: {}'.format(random))



print('data + ones: {}'.format(data + ones))
print('data - ones: {}'.format(data - ones))
print('data * ones: {}'.format(data * ones))
print('data / ones: {}'.format(data / ones))
print('data * 1.5: {}'.format(data * 1.5))
print('data ** 2: {}'.format(data ** 2))
print('10 * np.sin(a): {}'.format(10 * np.sin(data)))
print('data < 35: {}'.format(data < 35))

a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
print('a (before): {}'.format(a))
print('b (before): {}'.format(b))
a *= 3

print('a (after): {}'.format(a))
b += a
print('b (after): {}'.format(b))


# Matrix Operations

data = np.arange(1,11,1).reshape(2,5) # array([[1, 2, 3, 4, 5],[6,7,8,9,10]])
ones = np.ones((2,5))
data_2d = np.array([[1,2],[3,4]])
twos = np.full((2,5),2)

print('data: {}'.format(data))
print('ones: {}'.format(ones))
print('data_2d: {}'.format(data_2d))
print('twos: {}'.format(twos))

print('data + ones (element-wise): {}'.format(data + ones))
print('data - ones (element-wise): {}'.format(data - ones))
print('data * twos (element-wise): {}'.format(data * twos))
print('data / twos (element-wise): {}'.format(data / twos))
print('data + 1.5 (element-wise): {}'.format(data + 1.5))
print('data @ np.ones((5,2)) (matrix product): {}'.format(data @ np.ones((5,2))))
ones_b = np.ones((5,2))
print('data.dot(ones_b))(dot product): {}'.format(data.dot(ones_b)))
print('np.eye(4): {}'.format(np.eye(4))) # same as np.identity(4)



data: [1 2 3 4 5]
ones: [1. 1. 1. 1. 1.]
zeros: [0. 0. 0. 0. 0.]
random: [0.1140144  0.58789542 0.67183496 0.98335075 0.50673281]
data + ones: [2. 3. 4. 5. 6.]
data - ones: [0. 1. 2. 3. 4.]
data * ones: [1. 2. 3. 4. 5.]
data / ones: [1. 2. 3. 4. 5.]
data * 1.5: [1.5 3.  4.5 6.  7.5]
data ** 2: [ 1  4  9 16 25]
10 * np.sin(a): [ 8.41470985  9.09297427  1.41120008 -7.56802495 -9.58924275]
data < 35: [ True  True  True  True  True]
a (before): [[1 1 1]
 [1 1 1]]
b (before): [[0.69726775 0.79829502 0.36415572]
 [0.48612794 0.51260749 0.55184129]]
a (after): [[3 3 3]
 [3 3 3]]
b (after): [[3.69726775 3.79829502 3.36415572]
 [3.48612794 3.51260749 3.55184129]]
data: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
ones: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
data_2d: [[1 2]
 [3 4]]
twos: [[2 2 2 2 2]
 [2 2 2 2 2]]
data + ones (element-wise): [[ 2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11.]]
data - ones (element-wise): [[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
data * twos (element-wise): [[ 2  4  6  8 10]
 [12 14 

### Indexing operations

In [8]:
data = np.array([[1, 2, 3, 4, 5],[6,7,8,9,10]])
print('data: {}'.format(data))
print('data[0]: {}'.format(data[0]))
print('data[1]: {}'.format(data[1]))
print('data[0:2]: {}'.format(data[0:2]))
print('data[1:]: {}'.format(data[1:]))

data = np.array([[1,2],[3,4],[5,6]])

print('data: {}'.format(data))
print('data[0,1]: {}'.format(data[0,1]))
print('data[1:3]: {}'.format(data[1:3]))
print('data[0:2,0]: {}'.format(data[0:2,0]))


data: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
data[0]: [1 2 3 4 5]
data[1]: [ 6  7  8  9 10]
data[0:2]: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
data[1:]: [[ 6  7  8  9 10]]
data: [[1 2]
 [3 4]
 [5 6]]
data[0,1]: 2
data[1:3]: [[3 4]
 [5 6]]
data[0:2,0]: [1 3]


### Calculations

- min: Return the minimum along a given axis  
- max: Return the maximum along a given axis  
- sum: Return the sum of the array elements over the given axis  
- prod: Return the product of array elements over a given axis  
- median: Compute the median along the specified axis  
- average: Compute the weighted average along the specified axis  
- mean: Returns the average of the array elements along given axis  
- std: Returns the standard deviation of the array elements along given axis  
- var: Returns the variance of the array elements, along given axis
- trace: Return the sum along diagonals of the array  

In [9]:
data = np.array([[1, 2, 3, 4, 5],[6,7,8,9,10]])
print('data: {}'.format(data))

print('data.max(): {}'.format(data.max()))
print('data.min(): {}'.format(data.min()))

print('data.sum(): {}'.format(data.sum()))
print('data.prod(): {}'.format(data.prod()))



print('data.mean(): {}'.format(data.mean()))
print('data.std(): {}'.format(data.std()))
print('data.var(): {}'.format(data.var()))


print('data.trace(): {}'.format(data.trace()))

print('data.max(): {}'.format(data.max()))
print('data.min(): {}'.format(data.min()))
print('data.sum(): {}'.format(data.sum()))


print('data.max(axis=0): {}'.format(data.max(axis=0)))
print('data.max(axis=1): {}'.format(data.max(axis=1)))
print('data.min(axis=0): {}'.format(data.min(axis=0)))
print('data.min(axis=1): {}'.format(data.min(axis=1)))
print('data.sum(axis=0): {}'.format(data.sum(axis=0)))
print('data.sum(axis=1): {}'.format(data.sum(axis=1)))

print('np.median(data): {}'.format(np.median(data)))
print('np.average(data): {}'.format(np.average(data)))


data: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
data.max(): 10
data.min(): 1
data.sum(): 55
data.prod(): 3628800
data.mean(): 5.5
data.std(): 2.8722813232690143
data.var(): 8.25
data.trace(): 8
data.max(): 10
data.min(): 1
data.sum(): 55
data.max(axis=0): [ 6  7  8  9 10]
data.max(axis=1): [ 5 10]
data.min(axis=0): [1 2 3 4 5]
data.min(axis=1): [1 6]
data.sum(axis=0): [ 7  9 11 13 15]
data.sum(axis=1): [15 40]
np.median(data): 5.5
np.average(data): 5.5


### Universal functions

- add: Add arguments element-wise  
- subtract: Subtract arguments, element-wise  
- multiply: Multiply arguments element-wise  
- divide: Returns a true division of the inputs, element-wise  
- power: First array elements raised to powers from second array, element-wise  
- exp: Calculate the exponential of all elements in the input array   
- square: Return the element-wise square of the input  
- sqrt: Return the non-negative square-root of an array, element-wise  
- log: Natural logarithm, element-wise  
- log2: Base-2 logarithm of x  
- mod: Return element-wise remainder of division  
- gcd: Returns the greatest common divisor of |x1| and |x2|  
- lcm: Returns the lowest common multiple of |x1| and |x2|  

In [10]:
a = np.arange(1,4)
b = np.arange(4,7)

print('a: {}'.format(a))
print('b: {}'.format(b))


print('np.add(a,b): {}'.format(np.add(a,b)))
print('np.subtract(a,b): {}'.format(np.subtract(a,b)))
print('np.multiply(a,b): {}'.format(np.multiply(a,b)))
print('np.divide(a,b): {}'.format(np.divide(a,b)))
print('np.power(a,b): {}'.format(np.power(a,b)))
print('np.mod(a,b): {}'.format(np.mod(a,b)))

print('np.gcd(a,b): {}'.format(np.gcd(a,b)))
print('np.lcm(a,b): {}'.format(np.lcm(a,b)))

print('np.exp(a): {}'.format(np.exp(a)))
print('np.square(a): {}'.format(np.square(a)))
print('np.sqrt(a): {}'.format(np.sqrt(a)))
print('np.log(a): {}'.format(np.log(a)))
print('np.log2(a): {}'.format(np.log2(a)))


a: [1 2 3]
b: [4 5 6]
np.add(a,b): [5 7 9]
np.subtract(a,b): [-3 -3 -3]
np.multiply(a,b): [ 4 10 18]
np.divide(a,b): [0.25 0.4  0.5 ]
np.power(a,b): [  1  32 729]
np.mod(a,b): [1 2 3]
np.gcd(a,b): [1 1 3]
np.lcm(a,b): [ 4 10  6]
np.exp(a): [ 2.71828183  7.3890561  20.08553692]
np.square(a): [1 4 9]
np.sqrt(a): [1.         1.41421356 1.73205081]
np.log(a): [0.         0.69314718 1.09861229]
np.log2(a): [0.        1.        1.5849625]


### Trigonometric Functions

- sin: Trigonometric sine, element-wise  
- cos: Cosine element-wise  
- tan: Compute tangent element-wise  
- sinh: Hyperbolic sine, element-wise  
- cosh: Hyperbolic cosine, element-wise  
- tanh: Compute hyperbolic tangent element-wise  


In [11]:
print('np.sin(np.pi/2.): {}'.format(np.sin(np.pi/2.)))
print('np.cos(np.pi/2.): {}'.format(np.cos(np.pi/2.)))
print('np.tan(np.pi/2.): {}'.format(np.tan(np.pi/2.)))
print('np.sinh(np.pi/2.): {}'.format(np.sinh(np.pi/2.)))
print('np.cosh(np.pi/2.): {}'.format(np.cosh(np.pi/2.)))
print('np.tanh(np.pi/2.): {}'.format(np.tanh(np.pi/2.)))

np.sin(np.pi/2.): 1.0
np.cos(np.pi/2.): 6.123233995736766e-17
np.tan(np.pi/2.): 1.633123935319537e+16
np.sinh(np.pi/2.): 2.3012989023072947
np.cosh(np.pi/2.): 2.5091784786580567
np.tanh(np.pi/2.): 0.9171523356672744


### Comparison Functions

- greater: Return the truth value of (x1 > x2) element-wise    
- greater_equal: Return the truth value of (x1 >= x2) element-wise  
- less: Return the truth value of (x1 < x2) element-wise  
- less_equal: Return the truth value of (x1 =< x2) element-wise  
- not_equal: Return (x1 != x2) element-wise  
- equal: Return (x1 == x2) element-wise  

In [12]:
a = np.arange(1,4)
b = np.arange(4,7)

print('np.greater(a,b): {}'.format(np.greater(a,b)))
print('np.greater_equal(a,b): {}'.format(np.greater_equal(a,b)))
print('np.less(a,b): {}'.format(np.less(a,b)))
print('np.less_equal(a,b): {}'.format(np.less_equal(a,b)))
print('np.not_equal(a,b): {}'.format(np.not_equal(a,b)))
print('np.equal(a,b): {}'.format(np.equal(a,b)))

np.greater(a,b): [False False False]
np.greater_equal(a,b): [False False False]
np.less(a,b): [ True  True  True]
np.less_equal(a,b): [ True  True  True]
np.not_equal(a,b): [ True  True  True]
np.equal(a,b): [False False False]


### Broadcasting

In numpy the dimension requirements for elementwise operations are relaxed via a mechanism called broadcasting. Two matrices are compatible if the corresponding dimensions in each matrix (rows vs rows, columns vs columns) meet the following requirements:

- The dimensions are equal, or
- One dimension is of size 1

In [13]:
data = np.array([[1, 2, 3, 4, 5],[6,7,8,9,10]])
ones = np.ones(5)

print('data: {}'.format(data))
print('ones: {}'.format(ones))

print('data + ones: {}'.format(data + ones))

data: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
ones: [1. 1. 1. 1. 1.]
data + ones: [[ 2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11.]]


### Dot product

Dot product of two arrays. Specifically,

If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).

If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

If either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred.

If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.

If a is an N-D array and b is an M-D array (where M>=2), it is a sum product over the last axis of a and the second-to-last axis of b:

dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

In [14]:
print('np.dot(3,4): {}'.format(np.dot(3,4)))

a = np.array([1,2,3])
b = np.array([1,2,3])

c = np.array([[1,2],[3,4],[5,6]])
d = np.array([[1,2,3],[4,5,6]])

print('a.dot(b): {}'.format(a.dot(b)))
print('b.dot(c): {}'.format(b.dot(c)))
print('c.dot(d): {}'.format(c.dot(d)))

e = np.array([[1,2],[3,4]])
f = np.array([[1,2],[3,4]])
print('e.dot(f): {}'.format(e.dot(f)))
print('e @ f: {}'.format(e@f))

g = np.array([[1,2],[3,4]])
h = 2
print('np.dot(g,h): {}'.format(np.dot(g,h)))
print('g * h: {}'.format(g*h))


i = np.array([[1,2],[3,4],[5,6]])
j = np.array([[1,2],[3,4]])
print('i.dot(j): {}'.format(i.dot(j)))

k = np.arange(3*4*5*6).reshape((3,4,5,6))
l = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
print('np.dot(k, l)[2,3,2,1,2,2]: {}'.format(np.dot(k, l)[2,3,2,1,2,2]))
print('sum(k[2,3,2,:] * l[1,2,:,2]): {}'.format(sum(k[2,3,2,:] * l[1,2,:,2])))

m = np.array([[1,7],[2,4]])
n = np.array([[3,3],[5,2]])

print('m: {}'.format(m))
print('n * b: {}'.format(n))

print('m.dot(n): {}'.format(m.dot(n)))
print('m @ n: {}'.format(m@n))
print('m * n: {}'.format(m * n))


np.dot(3,4): 12
a.dot(b): 14
b.dot(c): [22 28]
c.dot(d): [[ 9 12 15]
 [19 26 33]
 [29 40 51]]
e.dot(f): [[ 7 10]
 [15 22]]
e @ f: [[ 7 10]
 [15 22]]
np.dot(g,h): [[2 4]
 [6 8]]
g * h: [[2 4]
 [6 8]]
i.dot(j): [[ 7 10]
 [15 22]
 [23 34]]
np.dot(k, l)[2,3,2,1,2,2]: 499128
sum(k[2,3,2,:] * l[1,2,:,2]): 499128
m: [[1 7]
 [2 4]]
n * b: [[3 3]
 [5 2]]
m.dot(n): [[38 17]
 [26 14]]
m @ n: [[38 17]
 [26 14]]
m * n: [[ 3 21]
 [10  8]]


### Inner

Ordinary inner product of vectors for 1-D arrays (without complex conjugation), in higher dimensions a sum product over the last axes.

In [15]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print('np.inner(a, b): {}'.format(np.inner(a, b)))
print('sum(a[:] * b[:]): {}'.format(sum(a[:] * b[:])))

c = np.array([[1,2,3],[4,5,6]])
d = np.array([[1,2,3],[4,5,6]])
print('np.inner(c, d): {}'.format(np.inner(c, d)))
print('sum(c[:] * d[:]): {}'.format(sum(c[:] * d[:])))


np.inner(a, b): 32
sum(a[:] * b[:]): 32
np.inner(c, d): [[14 32]
 [32 77]]
sum(c[:] * d[:]): [17 29 45]


### Other Operations 

- copy: Return a copy of the array  
- fill: Fill the array with a scalar value

In [16]:
x = np.array([[1,2,3],[4,5,6]])
print('x (initial): {}'.format(x))
y = x.copy()
print('y (after copy): {}'.format(y))
x.fill(0)
print('x (after fill): {}'.format(x))
print('y (after fill): {}'.format(y))


x (initial): [[1 2 3]
 [4 5 6]]
y (after copy): [[1 2 3]
 [4 5 6]]
x (after fill): [[0 0 0]
 [0 0 0]]
y (after fill): [[1 2 3]
 [4 5 6]]


### Formula evaluations

In [17]:
# formula: mean-square-error = (1/n) sigma (i=1 to n)square of ((prediction(i) - y(i)))
predictions = np.array([1,1,1])
labels = np.array([1,2,3])
n=3

error=(1/n) * np.sum(np.square(predictions-labels))

print('error: {}'.format(error))


error: 1.6666666666666665
