# Introduction to NumPy - Part 01

Purpose of this notebook is to provide an introduction to NumPy. 
This is part 1 of the series.

Before we explore more on NumPy, lets import NumPy and print the version being used

In [14]:
import numpy as np
print('numpy version: {}'.format(np.__version__))

numpy version: 1.16.2


Array initialization

In [15]:
# initialize a numpy array
data = np.array([1, 2, 3, 4, 5])

# initialize an array with 5 ones
ones = np.ones(5)

# initialize an array with 5 zeros
zeros = np.zeros(5)

# initialize an array with 5 random numbers
random = np.random.random(5)

# print the arrays
print('data: {}'.format(data))
print('data.shape: {}'.format(data.shape))

print('ones: {}'.format(ones))
print('ones.shape: {}'.format(ones.shape))

print('zeros: {}'.format(zeros))
print('zeros.shape: {}'.format(zeros.shape))

print('random: {}'.format(random))
print('random.shape: {}'.format(random.shape))


data: [1 2 3 4 5]
data.shape: (5,)
ones: [1. 1. 1. 1. 1.]
ones.shape: (5,)
zeros: [0. 0. 0. 0. 0.]
zeros.shape: (5,)
random: [0.92058909 0.32292432 0.34403503 0.36371273 0.13475017]
random.shape: (5,)


Perform basic operations on arrays and print the results

In [16]:
add_result = data + ones
subtraction_result = data - ones
multiplication_result = data * ones
division_result = data / ones
element_multiplication_result =  data * 1.5

print('add_result: ', add_result)
print('subtraction_result: ', subtraction_result)
print('multiplication_result: ', multiplication_result)
print('division_result: ', division_result)
print('element_multiplication_result: ',element_multiplication_result)

add_result:  [2. 3. 4. 5. 6.]
subtraction_result:  [0. 1. 2. 3. 4.]
multiplication_result:  [1. 2. 3. 4. 5.]
division_result:  [1. 2. 3. 4. 5.]
element_multiplication_result:  [1.5 3.  4.5 6.  7.5]


Basic indexing operations

In [17]:
print('data: ',data)
print('data[0]: ',data[0])
print('data[1]: ',data[1])
print('data[0:2]: ',data[0:2])
print('data[1:]: ',data[1:])


data:  [1 2 3 4 5]
data[0]:  1
data[1]:  2
data[0:2]:  [1 2]
data[1:]:  [2 3 4 5]


Aggregation operations

In [18]:
print('data.max(): ',data.max())
print('data.min(): ',data.min())
print('data.sum(): ',data.sum())

data.max():  5
data.min():  1
data.sum():  15


In [19]:
data_2d = np.array([[1, 2, 3, 4, 5],[6,7,8,9,0]])
ones_2d = np.ones((2,5))
zeros_2d = np.zeros((2,5))
random_2d = np.random.random((2,5))

# print the arrays
print('data_2d: ',data_2d)
print('ones_2d: ',ones_2d)
print('zeros_2d: ',zeros_2d)
print('random_2d: ',random_2d)


data_2d:  [[1 2 3 4 5]
 [6 7 8 9 0]]
ones_2d:  [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
zeros_2d:  [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
random_2d:  [[0.03505572 0.34442154 0.33962285 0.44026611 0.86149997]
 [0.30587031 0.98381489 0.25107596 0.08137569 0.05600544]]


Matrix arithmetic

In [20]:
add_result_2d = data_2d + ones_2d
subtraction_result_2d  = data_2d - ones_2d
multiplication_result_2d  = data_2d * ones_2d
division_result_2d  = data_2d / ones_2d
element_multiplication_result_2d  = data_2d + 1.5

print('add_result_2d: ', add_result_2d)
print('subtraction_result_2d: ', subtraction_result_2d)
print('multiplication_result_2d: ', multiplication_result_2d)
print('division_result_2d: ', division_result_2d)
print('element_multiplication_result_2d: ',element_multiplication_result_2d)

add_result_2d:  [[ 2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10.  1.]]
subtraction_result_2d:  [[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8. -1.]]
multiplication_result_2d:  [[1. 2. 3. 4. 5.]
 [6. 7. 8. 9. 0.]]
division_result_2d:  [[1. 2. 3. 4. 5.]
 [6. 7. 8. 9. 0.]]
element_multiplication_result_2d:  [[ 2.5  3.5  4.5  5.5  6.5]
 [ 7.5  8.5  9.5 10.5  1.5]]


Matrix operations: broadcasting

In [21]:
ones_1d = np.ones(5)
print('ones_1d: ', ones_1d)
add_result_2d = data_2d + np.ones(5)
print('add_result_2d: ', add_result_2d)

ones_1d:  [1. 1. 1. 1. 1.]
add_result_2d:  [[ 2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10.  1.]]


Dot product

In [22]:
data_2 = np.array([1,2,3])
data_3 = np.array([1,2,3])
data_4 = np.array([[1,2],[1,2],[1,2]])
dot_product_result_1 = data_2.dot(data_3)
print('dot_product_result_1:',dot_product_result_1)
dot_product_result_2 = data_2.dot(data_4)
print('dot_product_result_2:',dot_product_result_2)


dot_product_result_1: 14
dot_product_result_2: [ 6 12]


Matrix indexing

In [23]:
data = np.array([[1,2],[3,4],[5,6]])
print('data: ',data)
print('data[0,1]: ',data[0,1])
print('data[1:3]: ',data[1:3])
print('data[0:2,0]: ',data[0:2,0])

data:  [[1 2]
 [3 4]
 [5 6]]
data[0,1]:  2
data[1:3]:  [[3 4]
 [5 6]]
data[0:2,0]:  [1 3]


Matrix aggregation

In [24]:
print('data.max(): ',data.max())
print('data.min(): ',data.min())
print('data.sum(): ',data.sum())

print('data.max(axis=0): ',data.max(axis=0))
print('data.max(axis=1): ',data.max(axis=1))

data.max():  6
data.min():  1
data.sum():  21
data.max(axis=0):  [5 6]
data.max(axis=1):  [2 4 6]


Transposing and reshaping

In [25]:
data = np.array([1,2,3,4,5,6])

print('data.reshape(2,3): ',data.reshape(2,3))
print('data.reshape(3,2): ',data.reshape(3,2))

data.reshape(2,3):  [[1 2 3]
 [4 5 6]]
data.reshape(3,2):  [[1 2]
 [3 4]
 [5 6]]


More dimensions

In [26]:
data_multi_ones = np.ones((4,3,2))
data_multi_zeros = np.zeros((4,3,2))
data_multi_random = np.random.random((4,3,2))

print('data_multi_ones: ',data_multi_ones)
print('data_multi_zeros: ',data_multi_zeros)
print('data_multi_random: ',data_multi_random)

data_multi_ones:  [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
data_multi_zeros:  [[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
data_multi_random:  [[[0.72535613 0.91444772]
  [0.39594296 0.49410375]
  [0.74145104 0.03007312]]

 [[0.99024105 0.72364944]
  [0.04851409 0.75274374]
  [0.78456259 0.93692941]]

 [[0.64504812 0.97807936]
  [0.41404032 0.26667585]
  [0.31517936 0.18102424]]

 [[0.96716937 0.22365156]
  [0.49191569 0.38951694]
  [0.78410031 0.03418828]]]


Formula evaluations

In [27]:
# formula: mean-square-error = (1/n) sigma (i=1 to n)square of ((prediction(i) - y(i)))
predictions = np.array([1,1,1])
labels = np.array([1,2,3])
n=3

error=(1/n) * np.sum(np.square(predictions-labels))
print('error: ', error)

error:  1.6666666666666665
