# Introduction to NumPy - Part 01

Purpose of this notebook is to provide an introduction to NumPy. 
This is part 1 of the series.

Before we explore more on NumPy, lets import NumPy and print the version being used

In [1]:
import numpy as np
print('numpy version: {}'.format(np.__version__))

numpy version: 1.16.2


### Array initialization

In [2]:
# initialize a numpy array
data_1d = np.array([1, 2, 3, 4, 5])
data_2d = np.array([[1, 2, 3, 4, 5],[6,7,8,9,10]], dtype='complex')

# initialize an array with 5 ones
ones = np.ones(5)
ones_like = np.ones_like(data_2d)

# initialize an array with 5 zeros
zeros = np.zeros(5)
zeros_like = np.zeros_like(data_2d)

full = np.full((5,5),3)
full_like = np.full_like(data_2d,3)

# initialize an array with 5 random numbers
random = np.random.random(5)


# print the arrays
print('data_1d: {}'.format(data_1d))
print('data_2d: {}'.format(data_2d))
print('ones: {}'.format(ones))
print('ones_like: {}'.format(ones_like))
print('zeros: {}'.format(zeros))
print('zeros_like: {}'.format(zeros_like))
print('full: {}'.format(full))
print('full_like: {}'.format(full_like))
print('random: {}'.format(random))

data_1d: [1 2 3 4 5]
data_2d: [[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j]
 [ 6.+0.j  7.+0.j  8.+0.j  9.+0.j 10.+0.j]]
ones: [1. 1. 1. 1. 1.]
ones_like: [[1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]]
zeros: [0. 0. 0. 0. 0.]
zeros_like: [[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]]
full: [[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]
full_like: [[3.+0.j 3.+0.j 3.+0.j 3.+0.j 3.+0.j]
 [3.+0.j 3.+0.j 3.+0.j 3.+0.j 3.+0.j]]
random: [0.59747663 0.81170168 0.01882931 0.17011757 0.86540345]


### Array properties

In [3]:
# initialize an array with 5 ones
ones = np.ones(10)

print('ones.shape: {}'.format(ones.shape))
print('ones.ndim: {}'.format(ones.ndim))
print('ones.size: {}'.format(ones.size))
print('ones.dtype: {}'.format(ones.dtype))
print('ones.itemsize: {}'.format(ones.itemsize))
print('ones.data: {}'.format(ones.data))


ones.shape: (10,)
ones.ndim: 1
ones.size: 10
ones.dtype: float64
ones.itemsize: 8
ones.data: <memory at 0x7fca8c1ce588>


### arange, reshape

In [4]:
a = np.arange(15)
b = np.arange(10,50,5)
c = np.arange(0,5,.2)

d = np.arange(15).reshape(3, 5)
e = np.arange(24).reshape(2,3,4)

print('a: {}'.format(a))
print('b: {}'.format(b))
print('c: {}'.format(c))
print('d: {}'.format(d))
print('e: {}'.format(e))


print('a.shape: {}'.format(a.shape))
print('a.ndim: {}'.format(a.ndim))
print('a.size: {}'.format(a.size))
print('a.dtype: {}'.format(a.dtype))
print('a.itemsize: {}'.format(a.itemsize))
print('a.data: {}'.format(a.data))
print('type(a): {}'.format(type(a)))

print('b.shape: {}'.format(b.shape))
print('b.ndim: {}'.format(b.ndim))
print('b.size: {}'.format(b.size))
print('b.dtype: {}'.format(b.dtype))
print('b.itemsize: {}'.format(b.itemsize))
print('b.data: {}'.format(b.data))
print('type(b): {}'.format(type(b)))

a: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
b: [10 15 20 25 30 35 40 45]
c: [0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8]
d: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
e: [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
a.shape: (15,)
a.ndim: 1
a.size: 15
a.dtype: int64
a.itemsize: 8
a.data: <memory at 0x7fca8c1ce648>
type(a): <class 'numpy.ndarray'>
b.shape: (8,)
b.ndim: 1
b.size: 8
b.dtype: int64
b.itemsize: 8
b.data: <memory at 0x7fca8c1ce648>
type(b): <class 'numpy.ndarray'>


 ### Basic Array operations

In [5]:
data = np.array([1, 2, 3, 4, 5])
ones = np.ones(5)
zeros = np.zeros(5)
random = np.random.random(5)

print('data: {}'.format(data))
print('ones: {}'.format(ones))
print('zeros: {}'.format(zeros))
print('random: {}'.format(random))



print('data + ones: {}'.format(data + ones))
print('data - ones: {}'.format(data - ones))
print('data * ones: {}'.format(data * ones))
print('data / ones: {}'.format(data / ones))
print('data * 1.5: {}'.format(data * 1.5))
print('data ** 2: {}'.format(data ** 2))
print('10 * np.sin(a): {}'.format(10 * np.sin(data)))
print('data < 35: {}'.format(data < 35))


data: [1 2 3 4 5]
ones: [1. 1. 1. 1. 1.]
zeros: [0. 0. 0. 0. 0.]
random: [0.21331029 0.4089961  0.00386302 0.84534162 0.4826643 ]
data + ones: [2. 3. 4. 5. 6.]
data - ones: [0. 1. 2. 3. 4.]
data * ones: [1. 2. 3. 4. 5.]
data / ones: [1. 2. 3. 4. 5.]
data * 1.5: [1.5 3.  4.5 6.  7.5]
data ** 2: [ 1  4  9 16 25]
10 * np.sin(a): [ 8.41470985  9.09297427  1.41120008 -7.56802495 -9.58924275]
data < 35: [ True  True  True  True  True]


### Basic indexing operations

In [6]:
data = np.array([[1, 2, 3, 4, 5],[6,7,8,9,10]])
print('data: {}'.format(data))
print('data[0]: {}'.format(data[0]))
print('data[1]: {}'.format(data[1]))
print('data[0:2]: {}'.format(data[0:2]))
print('data[1:]: {}'.format(data[1:]))


data: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
data[0]: [1 2 3 4 5]
data[1]: [ 6  7  8  9 10]
data[0:2]: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
data[1:]: [[ 6  7  8  9 10]]


### Aggregation operations

In [7]:
print('data.max(): {}'.format(data.max()))
print('data.min(): {}'.format(data.min()))
print('data.sum(): {}'.format(data.sum()))

data.max(): 10
data.min(): 1
data.sum(): 55


In [8]:
data_2d = np.array([[1, 2, 3, 4, 5],[6,7,8,9,10]])
ones_2d = np.ones((2,5))
zeros_2d = np.zeros((2,5))
random_2d = np.random.random((2,5))

# print the arrays
print('data_2d: {}'.format(data_2d))
print('ones_2d: {}'.format(ones_2d))
print('zeros_2d: {}'.format(zeros_2d))
print('random_2d: {}'.format(random_2d))


data_2d:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
ones_2d:  [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
zeros_2d:  [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
random_2d:  [[0.8478188  0.60507203 0.85682856 0.33776796 0.32651003]
 [0.60965244 0.26835289 0.29688594 0.76244703 0.10070204]]


### Matrix arithmetic/operation

In [9]:
data = np.array([[1, 2, 3, 4, 5],[6,7,8,9,10]])
ones = np.ones((2,5))
sqare = np.array([[1,2],[3,4]])

print('data: {}'.format(data))
print('ones: {}'.format(ones))
print('sqare: {}'.format(sqare))

print('data + ones: {}'.format(data + ones))
print('data - ones: {}'.format(data - ones))
print('data * ones (elementwise): {}'.format(data * ones))
print('data @ np.ones((5,2)) (matrix product): {}'.format(data @ np.ones((5,2))))
print('data.dot(np.ones((5,2)))(dot product): {}'.format(data.dot(np.ones((5,2)))))
print('data / ones: {}'.format(data / ones))
print('data + 1.5: {}'.format(data + 1.5))
print('data.transpose(): {}'.format(data.transpose())) # or data.T
print('np.linalg.inv(sqare): {}'.format(np.linalg.inv(sqare)))
print('np.eye(4): {}'.format(np.eye(4))) # same as np.identity(4)


data: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
ones: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
sqare: [[1 2]
 [3 4]]
data + ones: [[ 2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11.]]
data - ones: [[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
data * ones (elementwise): [[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
data @ np.ones((5,2)) (matrix product): [[15. 15.]
 [40. 40.]]
data.dot(np.ones((5,2)))(dot product): [[15. 15.]
 [40. 40.]]
data / ones: [[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
data + 1.5: [[ 2.5  3.5  4.5  5.5  6.5]
 [ 7.5  8.5  9.5 10.5 11.5]]
data.transpose(): [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
np.linalg.inv(sqare): [[-2.   1. ]
 [ 1.5 -0.5]]
np.eye(4): [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Matrix operations: broadcasting

In [10]:
data = np.array([[1, 2, 3, 4, 5],[6,7,8,9,10]])
ones = np.ones(5)

print('data: {}'.format(data))
print('ones: {}'.format(ones))


print('data + np.ones(5): {}'.format(data + np.ones(5)))

data: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
ones: [1. 1. 1. 1. 1.]
data + np.ones(5): [[ 2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11.]]


### Dot product

In [44]:
a = np.array([1,2,3])
b = np.array([1,2,3])

c = np.array([[1,2],[3,4],[5,6]])
d = np.array([[1,2,3],[4,5,6]])

e = np.array([[1,2],[3,4]])
f = np.array([[1,2],[3,4]])

g = np.array([[1,2],[3,4]])
h = 2

i = np.array([[1,2],[3,4],[5,6]])
j = np.array([[1,2],[3,4]])

k = np.arange(3*4*5*6).reshape((3,4,5,6))
l = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))

print('np.dot(3,4): {}'.format(np.dot(3,4)))

print('a.dot(b): {}'.format(a.dot(b)))
print('b.dot(c): {}'.format(b.dot(c)))
print('c.dot(d): {}'.format(c.dot(d)))

print('e.dot(f): {}'.format(e.dot(f)))
print('e @ f: {}'.format(e@f))

print('np.dot(g,h): {}'.format(np.dot(g,h)))
print('g * h: {}'.format(g*h))

print('i.dot(j): {}'.format(i.dot(j)))

print('np.dot(k, l)[2,3,2,1,2,2]: {}'.format(np.dot(k, l)[2,3,2,1,2,2]))
print('sum(k[2,3,2,:] * l[1,2,:,2]): {}'.format(sum(k[2,3,2,:] * l[1,2,:,2])))





np.dot(3,4): 12
a.dot(b): 14
b.dot(c): [22 28]
c.dot(d): [[ 9 12 15]
 [19 26 33]
 [29 40 51]]
e.dot(f): [[ 7 10]
 [15 22]]
e @ f: [[ 7 10]
 [15 22]]
np.dot(g,h): [[2 4]
 [6 8]]
g * h: [[2 4]
 [6 8]]
i.dot(j): [[ 7 10]
 [15 22]
 [23 34]]
np.dot(k, l)[2,3,2,1,2,2]: 499128
sum(k[2,3,2,:] * l[1,2,:,2]): 499128


### Matrix indexing

In [21]:
data = np.array([[1,2],[3,4],[5,6]])

print('data: {}'.format(data))
print('data[0,1]: {}'.format(data[0,1]))
print('data[1:3]: {}'.format(data[1:3]))
print('data[0:2,0]: {}'.format(data[0:2,0]))



data: [[1 2]
 [3 4]
 [5 6]]
data[0,1]: 2
data[1:3]: [[3 4]
 [5 6]]
data[0:2,0]: [1 3]


### Matrix aggregation

In [22]:
print('data.max(): {}'.format(data.max()))
print('data.min(): {}'.format(data.min()))
print('data.sum(): {}'.format(data.sum()))


print('data.max(axis=0): {}'.format(data.max(axis=0)))
print('data.max(axis=1): {}'.format(data.max(axis=1)))
print('data.min(axis=0): {}'.format(data.min(axis=0)))
print('data.min(axis=1): {}'.format(data.min(axis=1)))
print('data.sum(axis=0): {}'.format(data.sum(axis=0)))
print('data.sum(axis=1): {}'.format(data.sum(axis=1)))

data.max(): 6
data.min(): 1
data.sum(): 21
data.max(axis=0): [5 6]
data.max(axis=1): [2 4 6]
data.min(axis=0): [1 2]
data.min(axis=1): [1 3 5]
data.sum(axis=0): [ 9 12]
data.sum(axis=1): [ 3  7 11]


### Matrix : Transposing and reshaping

In [23]:
data = np.array([1,2,3,4,5,6])

print('data.reshape(2,3): {}'.format(data.reshape(2,3)))
print('data.reshape(3,2): {}'.format(data.reshape(3,2)))

data.reshape(2,3): [[1 2 3]
 [4 5 6]]
data.reshape(3,2): [[1 2]
 [3 4]
 [5 6]]


### More dimensions

In [17]:
ones = np.ones((4,3,2))
zeros = np.zeros((4,3,2))
random = np.random.random((4,3,2))

print('ones: {}'.format(ones))
print('zeros: {}'.format(zeros))
print('random: {}'.format(random))


ones: [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
zeros: [[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
random: [[[0.4891598  0.85623744]
  [0.32013945 0.69655404]
  [0.69969862 0.47349795]]

 [[0.5585266  0.22101148]
  [0.64059246 0.88991331]
  [0.16556285 0.37650944]]

 [[0.92928082 0.10627121]
  [0.3310009  0.07417723]
  [0.82973204 0.14709967]]

 [[0.88779145 0.28959006]
  [0.76229305 0.97249507]
  [0.98786565 0.77639312]]]


### Formula evaluations

In [24]:
# formula: mean-square-error = (1/n) sigma (i=1 to n)square of ((prediction(i) - y(i)))
predictions = np.array([1,1,1])
labels = np.array([1,2,3])
n=3

error=(1/n) * np.sum(np.square(predictions-labels))

print('error: {}'.format(error))


error: 1.6666666666666665


### Operations that modified the array itself (does not create a new array

In [19]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
print('a (before): {}'.format(a))
print('b (before): {}'.format(b))
a *= 3

print('a (after): {}'.format(a))
b += a
print('b (after): {}'.format(b))

a (before): [[1 1 1]
 [1 1 1]]
b (before): [[0.86874083 0.47199269 0.79725744]
 [0.52684217 0.90635866 0.18028307]]
a (after): [[3 3 3]
 [3 3 3]]
b (after): [[3.86874083 3.47199269 3.79725744]
 [3.52684217 3.90635866 3.18028307]]


### Universal functions (acts elementwise)


In [20]:
b = np.arange(3)
c = np.array([2., -1., 4.])
print('b: {}'.format(b))
print('c: {}'.format(c))

print('np.exp(b): {}'.format(np.exp(b)))
print('np.sqrt(b): {}'.format(np.sqrt(b)))
print('np.add(b,c): {}'.format(np.add(b,c)))

b: [0 1 2]
c: [ 2. -1.  4.]
np.exp(b): [1.         2.71828183 7.3890561 ]
np.sqrt(b): [0.         1.         1.41421356]
np.add(b,c): [2. 0. 6.]
